import Head from 'next/head';
import Image from 'next/image';
import CampLogin from '../assets/images/campLogin.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="row">
            <div class="col-xm-12 col-lg-6 ">
              <div className="d-none  d-lg-block">
                <Image src={CampLogin} alt="Hero Image" />
              </div>
            </div>
            <div className="col-xm-12 col-lg-6">
              <div style={{ marginTop: '30%' }} className="container">
                <div class="mb-5 mt-5">
                  <h2 className="text-center">Camp Login</h2>
                </div>
                <div class="mb-3 mt-5">
                  <label for="exampleFormControlInput1" class="form-label">
                    Camp ID
                  </label>
                  <input type="text" className="form-control form-control-lg" id="exampleFormControlInput1" placeholder="camp id" />
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">
                    Password
                  </label>
                  <input type="password" className="form-control form-control-lg" id="exampleFormControlInput1" placeholder="password" />
                </div>
                <div className="d-grid gap-2">
                  <button className="btn btn-success btn-lg" type="button">
                    Login
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
