# Generated by Django 4.0.5 on 2022-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family_data',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_members', models.IntegerField()),
                ('number_of_minors', models.IntegerField()),
                ('number_of_seniors', models.IntegerField()),
                ('number_of_women', models.IntegerField()),
                ('presence_of_pregnant', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('presence_of_disabled', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
    ]
