# Generated by Django 4.0.5 on 2022-10-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_data',
            name='phone_number',
            field=models.CharField(default=None, max_length=14),
        ),
    ]
