# Generated by Django 4.0.5 on 2022-10-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_model', '0003_remove_family_data_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_head_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=14)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_model.campmodel')),
            ],
        ),
    ]
