# Generated by Django 4.0.5 on 2022-10-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_model', '0004_campmodel_familymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('disabled', models.BooleanField(default=False)),
                ('phone_no', models.CharField(max_length=14)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_model.familymodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Family_data',
        ),
    ]
